### ISSUE TITLE
支持隐藏指示器，支持任意长度数组

### ISSUE THREAD

**Issue by anpoz** [moyokoo/Diooto#11]
现在有一点的局限性，数组超过15就不能显示后面的图片了

**Comment by moyokoo** [comment]
看了一下这个问题,该问题是由于recyclerview的view缓存的原因,导致无法获取到对应的view,可以手动传view解决

后期我会对recyclerview缓存部分进行适配

**Comment by moyokoo** [comment]
[1.23](https://github.com/moyokoo/Diooto/releases/tag/1.23) 版本已解决
