### ISSUE TITLE
安卓刘海屏，图片拖拽关闭，图片不能完全重合，会向下偏移一段距离。

### ISSUE THREAD

**Issue by online2** [moyokoo/Diooto#12]
[https://github.com/online2/SpanTextViewDemo/blob/master/image/1548919431054.gif](url)
手机机型：一加 onePlus6   onePlusA6000 系统9.0.1

**Comment by moyokoo** [comment]
全屏状态？我记得应该是没问题的,有时间我看下

**Comment by moyokoo** [comment]
config 设置 isFullScreen 看看

**Comment by online2** [comment]
直接下载官方demo就会出现，效果图我是有改了东西。

**Comment by moyokoo** [comment]
不论全屏还是没全屏 都会出现这个状况吗？

**Comment by online2** [comment]
表达有误，确切的来说是那种刘海屏幕的，我这边试了两部刘海屏的都会出现。
一加 onePlus6 onePlusA6000 系统9.0.1
vivo 系统y85a 8.1.0

**Comment by moyokoo** [comment]
1.21版本已经做了全面屏适配,可以进行测试
