### ISSUE TITLE
请问一下，本地图片如mipmap文件夹下的图片能加载吗

### ISSUE THREAD

**Issue by dary123** [moyokoo/Diooto#14]
请问一下，本地图片如mipmap文件夹下的图片能加载吗

**Comment by moyokoo** [comment]
只要将加载图片方式修改为加载本地的方法即可

**Comment by dary123** [comment]
怎么改加载方式呢

> 只要将加载图片方式修改为加载本地的方法即可

**Comment by xinnuo** [comment]
这个加载图片用的是这个：https://github.com/panpf/sketch  是可以加载本地图片的
