### ISSUE TITLE
依赖好了过后 sketchImageView 在XML中用不了，可以用原生的RV吗，不用你的WrapRecyclerView

### ISSUE THREAD

**Issue by GuoLiangjun123** [moyokoo/Diooto#16]

**Comment by moyokoo** [comment]
依赖使用 api  如果还用不了你需要去依赖 [sketch](https://github.com/panpf/sketch)

另外WrapRecyclerView 只是demo中用来测试 rv的头部的,完全可以替换

**Comment by GuoLiangjun123** [comment]
前辈提个bug 1.点击查看大图 然后退出大图游览 app状态栏变为了白色
                       2.点击查看大图 然后退出大图游览 从当前fragment切换到其他fragment，在其他fragment下拉刷新数据的时候，数据无法展示

**Comment by GuoLiangjun123** [comment]
> 依赖使用 api 如果还用不了你需要去依赖 [sketch](https://github.com/panpf/sketch)
> 
> 另外WrapRecyclerView 只是demo中用来测试 rv的头部的,完全可以替换

我刚才用公司的测试机跑了下，vivoX9s（7.1）会出现我周末说的这种情况。华为（5.1）只会出现状态栏问题。

**Comment by GuoLiangjun123** [comment]
> > 依赖使用 api 如果还用不了你需要去依赖 [sketch](https://github.com/panpf/sketch)
> > 另外WrapRecyclerView 只是demo中用来测试 rv的头部的,完全可以替换
> 
> 我刚才用公司的测试机跑了下，vivoX9s（7.1）会出现我周末说的这种情况。华为（5.1）只会出现状态栏问题。



> 依赖使用 api 如果还用不了你需要去依赖 [sketch](https://github.com/panpf/sketch)
> 
> 另外WrapRecyclerView 只是demo中用来测试 rv的头部的,完全可以替换

前辈不好意思 项目有点急。。。。可以回答一下怎么修改吗

**Comment by moyokoo** [comment]
1. 状态栏应该是bug,后续会做修改,你可以自己把状态栏状态更改回来

2. 这个问题最好能够提供代码或者源代码,否则我不知道具体原因是该库造成的还是什么
