### ISSUE TITLE
该项目会导致APP状态栏变成白色

### ISSUE THREAD

**Issue by 893193074** [moyokoo/Diooto#17]
该项目会导致APP状态栏变成白色，集成了多主题的APP无法适配

**Comment by GuoLiangjun123** [comment]
> 该项目会导致APP状态栏变成白色，集成了多主题的APP无法适配

我也是，请问您怎么解决的，而且我当前activity下的所有fragment的状态栏都变了，并且一片空白，看不见视图以及数据

**Comment by 893193074** [comment]
> > 该项目会导致APP状态栏变成白色，集成了多主题的APP无法适配
> 
> 我也是，请问您怎么解决的，而且我当前activity下的所有fragment的状态栏都变了，并且一片空白，看不见视图以及数据

不好意思我也没解决，我上周周末才导进项目，想等等看作者会不会帮忙解决

**Comment by 893193074** [comment]
> > 该项目会导致APP状态栏变成白色，集成了多主题的APP无法适配
> 
> 我也是，请问您怎么解决的，而且我当前activity下的所有fragment的状态栏都变了，并且一片空白，看不见视图以及数据

我解决了，在onFinish监听里手动改一下状态栏颜色就行了

**Comment by moyokoo** [comment]
后续会修复该bug

**Comment by Ximano** [comment]
> 后续会修复该bug

这个 问题什么时候修复，老哥

**Comment by moyokoo** [comment]
最近没时间修复,你可以先尝试上面的方法来解决

**Comment by GuoLiangjun123** [comment]
> > > 该项目会导致APP状态栏变成白色，集成了多主题的APP无法适配
> > 
> > 
> > 我也是，请问您怎么解决的，而且我当前activity下的所有fragment的状态栏都变了，并且一片空白，看不见视图以及数据
> 
> 我解决了，在onFinish监听里手动改一下状态栏颜色就行了
在fragment里面不行。。。。

**Comment by GuoLiangjun123** [comment]
> 后续会修复该bug

还有一个bug就是  点击图片方法过后再回来 图片会变大！（偶现）

**Comment by Ximano** [comment]
> > 后续会修复该bug
> 
> 还有一个bug就是 点击图片方法过后再回来 图片会变大！（偶现）

我觉得，直接处理ImageActivity比较好，应该可行(因为就是ImageActivity的出现影响了我们本来的ac状态栏的样式)，我是沉浸式状态栏，所以在onFinish回调中，直接ImmersionBar.hideStatusBar(window)，虽然会闪现一下，但是问题不大，勉强解决

**Comment by GuoLiangjun123** [comment]
> > > 后续会修复该bug
> > 
> > 
> > 还有一个bug就是 点击图片方法过后再回来 图片会变大！（偶现）
> 
> 我觉得，直接处理ImageActivity比较好，应该可行(因为就是ImageActivity的出现影响了我们本来的ac状态栏的样式)，我是沉浸式状态栏，所以在onFinish回调中，直接ImmersionBar.hideStatusBar(window)，虽然会闪现一下，但是问题不大，勉强解决

您好方便加个QQ吗，，，想请教一下解决办法

**Comment by Ximano** [comment]
@moyokoo 老哥，你要不要建个群，这个库需求还是挺大的。大家可以交流下现在遇到的问题，和以后的需求走向，谢谢大佬~

**Comment by moyokoo** [comment]
点击链接加入群聊【Diooto讨论群】：https://jq.qq.com/?_wv=1027&k=5rRPlqe

既然你们需要我就建一个

**Comment by moyokoo** [comment]
[1.22](https://github.com/moyokoo/Diooto/releases/tag/1.22) 解决沉浸式适配
