### ISSUE TITLE
这个库不提供自动更新大小 大小需要你的第三方库来进行确定

### ISSUE THREAD

**Issue by Ximano** [moyokoo/Diooto#18]
这个库不提供自动更新大小 大小需要你的第三方库来进行确定

_Originally posted by @moyokoo in https://github.com/moyokoo/Diooto/issues/1#issuecomment-436542771_

需要在哪个地方集成我的第三方播放器？

**Comment by moyokoo** [comment]
详细阅读文档 [视频模式](https://www.yuque.com/elune/blog/mdf88x#e5a2860e)
