### ISSUE TITLE
图片放大问题

### ISSUE THREAD

**Issue by lifuyuan123** [moyokoo/Diooto#2]
多张图片列表中，点开单张图片，手势放大图片发现布局的宽高已经定死，不能放大为全屏显示图片，只能在初始进入的图片大小范围内放大。

**Comment by moyokoo** [comment]
这个问题确实没考虑到,后续版本会加入

**Comment by lifuyuan123** [comment]
@moyokoo 嗯 点个赞

**Comment by moyokoo** [comment]
[https://github.com/moyokoo/Diooto/releases/tag/1.16](Diooto_1.16)
最新版本已经增加该功能,可以测试一下

**Comment by moyokoo** [comment]
16的手机估计都没什么人用了  如果你想改就把项目clone下来当依赖吧,代码量也不多

**Comment by lifuyuan123** [comment]
@moyokoo  嗯 ，大神有没有试过recyclerview嵌套recyclerview，最里层查看图片，打开和关闭图片动画效果和demo不一致。

**Comment by moyokoo** [comment]
有时间我测试下

**Comment by moyokoo** [comment]
测试过了  没有这个问题
注意代码的编写
`.views(mRecyclerView,R.id.srcImageView)`

**Comment by lifuyuan123** [comment]
@moyokoo  刚刚我也重新写了个demo发现没有问题，确实是因为传入item中imagview的id复制了一个错误的id导致的。谢谢大神如此细心和快速的回复！
