### ISSUE TITLE
显示图片会闪一下

### ISSUE THREAD

**Issue by kotle** [moyokoo/Diooto#22]
之前设置了drawable，然后去加载网络图片，加载完成之后，界面会闪一下，如果这张网络图片已经加载过一次，就不会闪一下。

**Comment by kotle** [comment]
导入源码，自己修改了下，已经修复了。

**Comment by dary123** [comment]
怎么修复的呢

**Comment by darkrevier** [comment]
@kotle 请问一下怎么修复的  我也遇到了同样的问题

**Comment by kotle** [comment]
> @kotle 请问一下怎么修复的 我也遇到了同样的问题

导入源码，需要修改源码，在他加载图片那里。

**Comment by darkrevier** [comment]
@kotle 哥们麻烦能贴一下具体的代码吗   目前我这没有头绪 看加载那得代码也没有需要改动的地方啊

**Comment by kotle** [comment]
我前两天刚好库删了，因为问题太多了，没得源码了。我记得当初在一个fragment里面修改的。

**Comment by kotle** [comment]
> @kotle 哥们麻烦能贴一下具体的代码吗 目前我这没有头绪 看加载那得代码也没有需要改动的地方啊

我已经把库删了，因为问题太多了，没得源码了。我记得当初在一个fragment里面修改的。他里面显示图片用第三方那个库sketch，你要解决的是这个库的缓存问题。

**Comment by darkrevier** [comment]
@kotle 他有两个方法一个是loadWithCache();还有一个是loadWithoutCache()。看了这个代码加载图片的回调显示 请问问题时出现在这里面吗

**Comment by kotle** [comment]
> @kotle 他有两个方法一个是loadWithCache();还有一个是loadWithoutCache()。看了这个代码加载图片的回调显示 请问问题时出现在这里面吗 还是你导入了sketch的源码做了修改

我也忘了，好几个月前改过的，不好意思。好像是缓存过就没问题。主要问题还是切换两张图片的不是无缝的。

**Comment by darkrevier** [comment]
@kotle 嗯 缓存的话是没有闪烁了 就是第一次加载的时候两张图片过度的时候闪
