### ISSUE TITLE
带头尾的布局把头尾都算进去了

### ISSUE THREAD

**Issue by dongchengBees360** [moyokoo/Diooto#4]
发现貌似不兼容带头尾的布局的recyclerview,也存在偶发性的图片崩溃,
![image](https://user-images.githubusercontent.com/37902378/49682886-d5c29c80-faf6-11e8-849d-7136c4e8e487.png)
刚开始接入的时候会有这个问题,后来情况就少了,不知道为啥.

**Comment by dongchengBees360** [comment]
还有个很奇怪的现象,图片缩小回到item位置时出现了错乱的情况,女生图片没问题,都是从消失的位置回去的,男生头像却是从各个角落回到item所在的位置,下面房屋的图片也没问题
![image](https://user-images.githubusercontent.com/37902378/49682995-bf1d4500-faf8-11e8-8f0f-cd7794641a76.png)
tupian

**Comment by moyokoo** [comment]
有没有gif看看位置错乱的问题

**Comment by moyokoo** [comment]
偶发性的问题是什么操作出现的

**Comment by dongchengBees360** [comment]
![66b33d17f8ac9ea957fc647dc6ca278a](https://user-images.githubusercontent.com/37902378/49683337-212c7900-fafe-11e8-8eb0-cfc8b8c2fa6c.gif)
哈哈,有点短,可以配合上图凑合着看吧

**Comment by moyokoo** [comment]
把你使用的代码 还有recyclerview的代码贴下

**Comment by dongchengBees360** [comment]
外面的是一层recyclerview嵌套一层viewpager+带有个尾巴的加号的recyclerview,显示的时候最后一张会显示一个黑色的蒙层
Diooto的用法我就是参照demo上的试了一下
![image](https://user-images.githubusercontent.com/37902378/49683486-cb0d0500-fb00-11e8-844d-131dd2bc136a.png)

**Comment by moyokoo** [comment]
男性部分的图片是不是正方形？是的话1.17版本已经解决,关于头部兼容问题,后续做修复

**Comment by moyokoo** [comment]
1.18版本已经修复头部问题
