### ISSUE TITLE
正方形图片问题

### ISSUE THREAD

**Issue by caiyoufei** [moyokoo/Diooto#5]
DragDiootoView 当走到310行代码时，会出现手动关闭滑动大图动画位置和大小不对的情况，下面GIF中的第一张放大的图
![1](https://user-images.githubusercontent.com/11989916/50263211-a3e2fb80-044f-11e9-8dc5-a720a15cc0fe.gif)

**Comment by caiyoufei** [comment]
![image](https://user-images.githubusercontent.com/11989916/50263578-7008d580-0451-11e9-8340-2315a30d830e.png)
貌似按照最后一张图流程走一下就OK了

**Comment by moyokoo** [comment]
最近比较忙，后续有时间会做修复

**Comment by moyokoo** [comment]
1.17版本已解决
