### ISSUE TITLE
非常棒的项目~

### ISSUE THREAD

**Issue by junchenChow** [moyokoo/Diooto#7]
看了下作者写的DragDiootoView 里面代码逻辑都很清晰。
在过渡到最小化的时候最后一帧的效果有点生硬，没有完整的复合到原来图片的位置上。
也看了好几个其他项目都不太完整。
有个小建议~~
如果把缩小的动作加上alpha的过渡 不用强行复合原来的位置 像微博效果妥协也不错。
现在就发现共享元素的过渡效果才有完美的复合动画。

**Comment by moyokoo** [comment]
没有完整的复合到原来图片的位置上, 这个是demo运行的效果还是？
图片的缩放 是有 alpha的过渡的,而且demo是可以完整地回到原来的状态

有没有图片演示一下你说的问题

**Comment by junchenChow** [comment]
换了好几个手机都没有完整的复合回去 都是快到原来位置的时候直接消失  就给我感觉有点生硬

**Comment by moyokoo** [comment]
你是直接下载master的代码运行的么

**Comment by junchenChow** [comment]
嗯~是的

**Comment by moyokoo** [comment]
效果不对,图片会完全复原才对

测试的机型是什么,系统版本是多少

**Comment by junchenChow** [comment]
我刚看了下gif上录的 这个还算复合的比较好了 其他位置的更加生硬
MI_8

**Comment by moyokoo** [comment]
正方形图片有没有问题？就是demi里的第一张

**Comment by moyokoo** [comment]
https://github.com/moyokoo/Diooto/releases/tag/1.18

下载apk试一下有没有问题,这个问题出现过历史版本 ,应该不会出现才对

**Comment by junchenChow** [comment]
这个1.18的效果更差。。。什么情况

**Comment by moyokoo** [comment]
还差一点是什么意思
和之前的问题一致吗,我用的小米6,测试是没问题的
